### ISSUE TITLE
Blank Page is Shown once I click on load enteries

### ISSUE THREAD

**Issue by ImDineshSaini** [clearbold/craftimport#8]
Documentation does not include any step to follow. I was just to confirm wheather this plugin has model enteries or not like Feedme.

**Comment by heymarkreeves** [comment]
Hello!

The craft import module is just starter code. To use it, you'll be updating all functions within the code to match your own section and type IDs, as well as section and field references.

A blank screen means one of the debug flags are turned on, which enable output along the process, or there's an `exit` statement left uncommented in there somewhere. If a debug flag is on, it should be outputting the values captured from the RSS feed and the reference IDs being found. If you're seeing nothing, it's likely not finding either.

Hope that helps! This isn't a supported, packaged plugin. It's something that I customize for every unique instance, and have shared with the community so others can do the same for their own needs.

Mark

**Comment by ImDineshSaini** [comment]
Where I have to write code. I just want to store RSS data in dB n wana see
in admin.

**Comment by heymarkreeves** [comment]
Per the README:

> All the magic happens in services/CraftImportService.php

**Comment by ImDineshSaini** [comment]
What I want to just store four fields that come via RSS, could you please help me to guide that- Should I have to create section first in the craft admin.

**Comment by heymarkreeves** [comment]
Sorry, no. You're asking for services that I charge money for, and that provide my household income. This is code I shared with the community, for developers to use as a starting point. If you're not familiar with Craft, you'll need to ramp up on your own.

**Comment by ImDineshSaini** [comment]
Hmm nothing like that I have asked about only function name as it is not available with the document. I can share the code that I have used with the help of Feed Me

**Comment by heymarkreeves** [comment]
You're asking whether you need to configure a Craft CMS installation first:

>  Should I have to create section first in the craft admin.

The code is a bridge between an XML feed and defined sections/fields, with examples from my work coded into it. If there is a flaw in the code, I'm happy to take a look, but to help configure a Craft site or be involved in customizing the import process, that's work I do for hire.

**Comment by ImDineshSaini** [comment]
It means I want to ask weather plugin has migration or not

**Comment by heymarkreeves** [comment]
@ImDineshSaini Is this work you're doing for a client? It may be best to point them in my direction to understand their needs.

This repository contains working code that you can drop into a CraftCMS installation and **modify** to conform to your _section_ & _field_ configuration, and your source RSS. It's code that **I customize** and use to support importing content into my clients' CraftCMS builds, and that I've shared so that others can learn from it or use it as a starting point. To ask if it "has migration" ignores that intent. This is code that runs a loop on the RSS source, and uses Craft's API on each XML node to create/update corresponding entries in Craft. It does not provide a UI for mapping source:target or other functions. It's just iterative code.
